CREATE TABLE BICICLETAS(idBicicleta INT PRIMARY KEY,añoFabricacion INT);

INSERT INTO BICICLETAS VALUES(1,2020);
INSERT INTO BICICLETAS VALUES(2,2019);
INSERT INTO BICICLETAS VALUES(3,2020);
INSERT INTO BICICLETAS VALUES(4,2021);


INSERT INTO BICICLETAS VALUES(5,1018);